---

# Redhat OS family installation tasks

- name: 'INSTALL | YUM | Install packages'
  become: True
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ logrotate_packages }}"
