---

# Main tasks file for logrotate role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::logrotate'
    - 'role::logrotate::init'
